project:
  type: website
  resources:
    - Resume.pdf
website:
  title: "Zhiyuan Zhou"
  site-url: https://zhiyuanzhou.netlify.app
  # description: "My website"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: about.qmd
      - text: "Recipes"
        href: recipes.qmd
  page-footer:
    left: "© Copyright 2025 Zhiyuan Zhou."
format:
  html:
    theme:
      light: cosmo
      dark: [darkly, theme-dark.scss]
    color-scheme: [light, dark]
    css: styles.css
    include-in-header:
      - text: |
          <script src="_freeze/themePersistence.js"></script>
    

    
