project:
  type: website
  resources:
    - Resume.pdf
website:
  title: "Zhiyuan Zhou"
  site-url: https://zhiyuanzhou.netlify.app
  description: "Portfolio and project documentation for Zhiyuan Zhou."
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: about.qmd
      - text: "Recipe Reference"
        href: recipes.qmd
  page-footer:
    left: "© 2025 Zhiyuan Zhou. All rights reserved."
format:
  html:
    theme:
      light: cosmo
      dark: [darkly, theme-dark.scss]
    color-scheme: [light, dark]
    css: styles.css
    include-in-header:
      - text: |
          <script src="_freeze/themePersistence.js"></script>
execute:
  freeze: auto
    
