project:
  type: website
  resources:
    - Resume.pdf
website:
  title: "Zhiyuan Zhou"
  site-url: https://zhiyuanzhou.netlify.app
  # description: "My website"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: about.qmd
      - text: "Recipes"
        href: recipes.qmd
  page-footer:
    left: "© Copyright 2025 Zhiyuan Zhou."
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    
